spring:
  application:
    name: client
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:
        myGroupId
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5