services:
  db:
    image: mysql
    container_name: mysqlDB
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_USER: Sina
      MYSQL_PASSWORD: abcd1234
      MYSQL_ROOT_PASSWORD: Sp@123456789
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - saga

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - saga

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - saga

  eureka:
    build: Eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    deploy:
      resources:
        limits:
          memory: 512m

  gateway:
    build: Gateway
    container_name: gateway
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [ eureka ]
    networks:
      - saga
    deploy:
      resources:
        limits:
          memory: 512m

  order:
    build: Order
    ports:
      - "8080:8080"
    container_name: order
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    depends_on: [ db, eureka ]
    deploy:
      resources:
        limits:
          memory: 512m

  payment:
    build: Payment
    ports:
      - "8081:8081"
    container_name: payment
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    depends_on: [ db, eureka ]
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  my-db:

networks:
  default:
  saga:
    driver: bridge