server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

  server:
    response-cache-update-interval-ms: 5000
    wait-time-in-ms-when-sync-empty: 0